	
		package TPVNUBEGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CajaFechaDTO 	    implements IDTO
	    {
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private String idCaja;
				public String getIdCaja () { return idCaja; } 
				public void setIdCaja  (String value) { idCaja = value;  } 
				    	 
				private String total;
				public String getTotal () { return total; } 
				public void setTotal  (String value) { total = value;  } 
				    	 
				private ArrayList<Integer> caja_oid;
				public ArrayList<Integer>  getCaja_oid () { return caja_oid; } 
				public void setCaja_oid (ArrayList<Integer> value) { caja_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("IdCaja", this.idCaja);
				
				
						  json.put("Total", this.total);
				

						if (this.caja_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.caja_oid.size(); ++i)
							{
								jsonArray.put(this.caja_oid.get(i));
							}
							json.put("Caja_oid", jsonArray);
						}
		
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	