	
		package TPVNUBEGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class CobroDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private float monto;
				public float getMonto () { return monto; } 
				public void setMonto  (float value) { monto = value;  } 
				    	 
				private Integer comanda_oid;
				public Integer  getComanda_oid () { return comanda_oid; } 
				public void setComanda_oid (Integer value) { comanda_oid = value;  } 
				    	 
				private Integer cliente_oid;
				public Integer  getCliente_oid () { return cliente_oid; } 
				public void setCliente_oid (Integer value) { cliente_oid = value;  } 
				    	 
				private Integer tipoCobro_oid;
				public Integer  getTipoCobro_oid () { return tipoCobro_oid; } 
				public void setTipoCobro_oid (Integer value) { tipoCobro_oid = value;  } 
				    	 
				private Integer caja_oid;
				public Integer  getCaja_oid () { return caja_oid; } 
				public void setCaja_oid (Integer value) { caja_oid = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Integer empleado_oid;
				public Integer  getEmpleado_oid () { return empleado_oid; } 
				public void setEmpleado_oid (Integer value) { empleado_oid = value;  } 
				    	 
				private Integer negocio_oid;
				public Integer  getNegocio_oid () { return negocio_oid; } 
				public void setNegocio_oid (Integer value) { negocio_oid = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("Monto", this.monto);
				

						if (this.comanda_oid != null)
						{
							json.put("Comanda_oid", this.comanda_oid.intValue());
						}

						if (this.cliente_oid != null)
						{
							json.put("Cliente_oid", this.cliente_oid.intValue());
						}

						if (this.tipoCobro_oid != null)
						{
							json.put("TipoCobro_oid", this.tipoCobro_oid.intValue());
						}

						if (this.caja_oid != null)
						{
							json.put("Caja_oid", this.caja_oid.intValue());
						}
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				

						if (this.empleado_oid != null)
						{
							json.put("Empleado_oid", this.empleado_oid.intValue());
						}

						if (this.negocio_oid != null)
						{
							json.put("Negocio_oid", this.negocio_oid.intValue());
						}
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	