	
		package TPVNUBEGenTpvhostRESTAzure.uiModels.DTO;
		
		import java.util.ArrayList;
		
		import org.json.JSONArray;
		import org.json.JSONException;
		import org.json.JSONObject;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.utils.*;
		import  TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;
		
		
		/**
		 * Code autogenerated. Do not modify this file.
		 */
		
		
		public class ComandaDTO 	    implements IDTO
	    {
				private Integer id;
				public Integer getId () { return id; } 
				public void setId  (Integer value) { id = value;  } 
				    	 
				private EstadoComanda estadoComanda;
				public EstadoComanda getEstadoComanda () { return estadoComanda; } 
				public void setEstadoComanda  (EstadoComanda value) { estadoComanda = value;  } 
				    	 
				private ArrayList<LineaComandaDTO> lineaComanda;
				public ArrayList<LineaComandaDTO> getLineaComanda () { return lineaComanda; } 
				public void setLineaComanda (ArrayList<LineaComandaDTO> value) { lineaComanda = value;  } 
				    	 
				private ArrayList<Integer> pago_oid;
				public ArrayList<Integer>  getPago_oid () { return pago_oid; } 
				public void setPago_oid (ArrayList<Integer> value) { pago_oid = value;  } 
				    	 
				private Integer mesa_oid;
				public Integer  getMesa_oid () { return mesa_oid; } 
				public void setMesa_oid (Integer value) { mesa_oid = value;  } 
				    	 
				private Integer factura_oid;
				public Integer  getFactura_oid () { return factura_oid; } 
				public void setFactura_oid (Integer value) { factura_oid = value;  } 
				    	 
				private java.util.Date fecha;
				public java.util.Date getFecha () { return fecha; } 
				public void setFecha  (java.util.Date value) { fecha = value;  } 
				    	 
				private Integer empleado_oid;
				public Integer  getEmpleado_oid () { return empleado_oid; } 
				public void setEmpleado_oid (Integer value) { empleado_oid = value;  } 
				    	 
				private Double total;
				public Double getTotal () { return total; } 
				public void setTotal  (Double value) { total = value;  } 
				    	 
	   
			    public JSONObject toJSON ()
				{
					JSONObject json = new JSONObject();
					
					try
					{
				
						  json.put("Id", this.id.intValue());
				
				
						  json.put("EstadoComanda", this.estadoComanda.getRawValue());
				

						if (this.lineaComanda != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.lineaComanda.size(); ++i)
							{
								jsonArray.put(this.lineaComanda.get(i).toJSON());
							}
							json.put("LineaComanda", jsonArray);
						}

						if (this.pago_oid != null)
						{
							JSONArray jsonArray = new JSONArray();
							for (int i = 0; i < this.pago_oid.size(); ++i)
							{
								jsonArray.put(this.pago_oid.get(i));
							}
							json.put("Pago_oid", jsonArray);
						}
		

						if (this.mesa_oid != null)
						{
							json.put("Mesa_oid", this.mesa_oid.intValue());
						}

						if (this.factura_oid != null)
						{
							json.put("Factura_oid", this.factura_oid.intValue());
						}
				
						  json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
				

						if (this.empleado_oid != null)
						{
							json.put("Empleado_oid", this.empleado_oid.intValue());
						}
				
						  json.put("Total", this.total);
				
						
					}
					catch (JSONException e)
					{
						e.printStackTrace();
					}
				
				return json;
			}
		
			// endregion
		}
	   
	   
	   
		
	