
package TPVNUBEGenEmpleadoRESTAzure.uiModels.DTOA;

import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CajaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private Double fondo;
	public Double getFondo () { return fondo; }
	public void setFondo (Double fondo) { this.fondo = fondo; }
	
	
	/* Rol: Caja o--> Pago */
	private ArrayList<PagoDTOA> cobros;
	public ArrayList<PagoDTOA> getCobros () { return cobros; }
	public void setCobros (ArrayList<PagoDTOA> cobros) { this.cobros = cobros; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CajaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Fondo")))
			{
			 
			 	String stringDouble = String.valueOf(json.opt("Fondo"));
 				this.fondo = Double.parseDouble(stringDouble);
			 
			}
			

			JSONObject jsonCobros = json.optJSONObject("Cobros");
			if (jsonCobros != null)
			{
				PagoDTOA tmp = new PagoDTOA();
				tmp.setFromJSON(jsonCobros);
				this.cobros = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.fondo != null)
			json.put("Fondo", this.fondo);
		
			

			if (this.cobros != null)
			{
				json.put("Cobros", this.cobros.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CajaDTO dto = new CajaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setFondo (this.getFondo());

		
		
		// Roles
					// TODO: from DTOA [ Cobros ] (dataType : ArrayList<PagoDTOA>) to DTO [ Cobro ]
		
		
		return dto;
	}

	// endregion
}

	