
package TPVNUBEGenEmpleadoRESTAzure.uiModels.DTOA;

import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class CajeroDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	
	/* Rol: Cajero o--> Caja */
	private ArrayList<CajaDTOA> cajas;
	public ArrayList<CajaDTOA> getCajas () { return cajas; }
	public void setCajas (ArrayList<CajaDTOA> cajas) { this.cajas = cajas; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public CajeroDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			
			

			JSONArray arrayCajas = json.optJSONArray("Cajas");
			if (arrayCajas != null)
			{
				this.cajas = new ArrayList<CajaDTOA>();
				for (int i = 0; i < arrayCajas.length(); ++i)
				{
					JSONObject subJson = (JSONObject) arrayCajas.opt(i);
					CajaDTOA tmp = new CajaDTOA();
					tmp.setFromJSON(subJson);
					this.cajas.add(tmp);
				}
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
			

			if (this.cajas != null)
			{
				JSONArray jsonArray = new JSONArray();
				for (int i = 0; i < this.cajas.size(); ++i)
				{
					jsonArray.put(this.cajas.get(i).toJSON());
				}
				json.put("Cajas", jsonArray);
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CajeroDTO dto = new CajeroDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
		
		
		// Roles
					// TODO: from DTOA [ Cajas ] (dataType : ArrayList<CajaDTOA>) to DTO [ Caja ]
		
		
		return dto;
	}

	// endregion
}

	