
package TPVNUBEGenEmpleadoRESTAzure.uiModels.DTOA;

import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class ComandaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private java.util.Date fecha;
	public java.util.Date getFecha () { return fecha; }
	public void setFecha (java.util.Date fecha) { this.fecha = fecha; }
	
	private Double total;
	public Double getTotal () { return total; }
	public void setTotal (Double total) { this.total = total; }
	
	private EstadoComanda estadoComanda;
	public EstadoComanda getEstadoComanda () { return estadoComanda; }
	public void setEstadoComanda (EstadoComanda estadoComanda) { this.estadoComanda = estadoComanda; }
	
	private String pdf;
	public String getPdf () { return pdf; }
	public void setPdf (String pdf) { this.pdf = pdf; }
	
	
	/* Rol: Comanda o--> Factura */
	private FacturaDTOA factura;
	public FacturaDTOA getFactura () { return factura; }
	public void setFactura (FacturaDTOA factura) { this.factura = factura; }

	/* Rol: Comanda o--> Mesa */
	private MesaDTOA mesaOfComanda;
	public MesaDTOA getMesaOfComanda () { return mesaOfComanda; }
	public void setMesaOfComanda (MesaDTOA mesaOfComanda) { this.mesaOfComanda = mesaOfComanda; }

	/* Rol: Comanda o--> LineaComanda */
	private ArrayList<LineaComandaDTOA> allLineaComandaOfComanda;
	public ArrayList<LineaComandaDTOA> getAllLineaComandaOfComanda () { return allLineaComandaOfComanda; }
	public void setAllLineaComandaOfComanda (ArrayList<LineaComandaDTOA> allLineaComandaOfComanda) { this.allLineaComandaOfComanda = allLineaComandaOfComanda; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public ComandaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Fecha")))
			{
			 
			 	String stringDate = (String) json.opt("Fecha");
				this.fecha = DateUtils.stringToDateFormat(stringDate);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Total")))
			{
			 
			 	String stringDouble = String.valueOf(json.opt("Total"));
 				this.total = Double.parseDouble(stringDouble);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("EstadoComanda")))
			{
				int enumRawValue = (int) json.opt("EstadoComanda");
				this.estadoComanda = EstadoComanda.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Pdf")))
			{
			 
				this.pdf = (String) json.opt("Pdf");
			 
			}
			

			JSONObject jsonFactura = json.optJSONObject("Factura");
			if (jsonFactura != null)
			{
				FacturaDTOA tmp = new FacturaDTOA();
				tmp.setFromJSON(jsonFactura);
				this.factura = tmp;
			}


			JSONObject jsonMesaOfComanda = json.optJSONObject("MesaOfComanda");
			if (jsonMesaOfComanda != null)
			{
				MesaDTOA tmp = new MesaDTOA();
				tmp.setFromJSON(jsonMesaOfComanda);
				this.mesaOfComanda = tmp;
			}


			JSONObject jsonAllLineaComandaOfComanda = json.optJSONObject("AllLineaComandaOfComanda");
			if (jsonAllLineaComandaOfComanda != null)
			{
				LineaComandaDTOA tmp = new LineaComandaDTOA();
				tmp.setFromJSON(jsonAllLineaComandaOfComanda);
				this.allLineaComandaOfComanda = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.fecha != null)
			json.put("Fecha", DateUtils.dateToFormatString(this.fecha));
		
		
		  if (this.total != null)
			json.put("Total", this.total);
		
		
		  if (this.estadoComanda != null)
			json.put("EstadoComanda", this.estadoComanda.getRawValue());
		
		
		  if (this.pdf != null)
			json.put("Pdf", this.pdf);
		
			

			if (this.factura != null)
			{
				json.put("Factura", this.factura.toJSON());
			}


			if (this.mesaOfComanda != null)
			{
				json.put("MesaOfComanda", this.mesaOfComanda.toJSON());
			}


			if (this.allLineaComandaOfComanda != null)
			{
				json.put("AllLineaComandaOfComanda", this.allLineaComandaOfComanda.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		ComandaDTO dto = new ComandaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setFecha (this.getFecha());

	dto.setTotal (this.getTotal());

	dto.setEstadoComanda (this.getEstadoComanda());

	dto.setPdf (this.getPdf());

		
		
		// Roles
					// TODO: from DTOA [ Factura ] (dataType : FacturaDTOA) to DTO [ Factura ]
					// TODO: from DTOA [ MesaOfComanda ] (dataType : MesaDTOA) to DTO [ Mesa ]
					// TODO: from DTOA [ AllLineaComandaOfComanda ] (dataType : ArrayList<LineaComandaDTOA>) to DTO [ LineaComanda ]
		
		
		return dto;
	}

	// endregion
}

	