
package TPVNUBEGenEmpleadoRESTAzure.uiModels.DTOA;

import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class LineaComandaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private Integer cantidad;
	public Integer getCantidad () { return cantidad; }
	public void setCantidad (Integer cantidad) { this.cantidad = cantidad; }
	
	
	/* Rol: LineaComanda o--> Plato */
	private PlatoDTOA platoOfLineaComanda;
	public PlatoDTOA getPlatoOfLineaComanda () { return platoOfLineaComanda; }
	public void setPlatoOfLineaComanda (PlatoDTOA platoOfLineaComanda) { this.platoOfLineaComanda = platoOfLineaComanda; }

	/* Rol: LineaComanda o--> Menu */
	private MenuDTOA menuOfLineaComanda;
	public MenuDTOA getMenuOfLineaComanda () { return menuOfLineaComanda; }
	public void setMenuOfLineaComanda (MenuDTOA menuOfLineaComanda) { this.menuOfLineaComanda = menuOfLineaComanda; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public LineaComandaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Cantidad")))
			{
			 
				this.cantidad = (Integer) json.opt("Cantidad");
			 
			}
			

			JSONObject jsonPlatoOfLineaComanda = json.optJSONObject("PlatoOfLineaComanda");
			if (jsonPlatoOfLineaComanda != null)
			{
				PlatoDTOA tmp = new PlatoDTOA();
				tmp.setFromJSON(jsonPlatoOfLineaComanda);
				this.platoOfLineaComanda = tmp;
			}


			JSONObject jsonMenuOfLineaComanda = json.optJSONObject("MenuOfLineaComanda");
			if (jsonMenuOfLineaComanda != null)
			{
				MenuDTOA tmp = new MenuDTOA();
				tmp.setFromJSON(jsonMenuOfLineaComanda);
				this.menuOfLineaComanda = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.cantidad != null)
			json.put("Cantidad", this.cantidad.intValue());
		
			

			if (this.platoOfLineaComanda != null)
			{
				json.put("PlatoOfLineaComanda", this.platoOfLineaComanda.toJSON());
			}


			if (this.menuOfLineaComanda != null)
			{
				json.put("MenuOfLineaComanda", this.menuOfLineaComanda.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		LineaComandaDTO dto = new LineaComandaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setCantidad (this.getCantidad());

		
		
		// Roles
					// TODO: from DTOA [ PlatoOfLineaComanda ] (dataType : PlatoDTOA) to DTO [ Plato ]
					// TODO: from DTOA [ MenuOfLineaComanda ] (dataType : MenuDTOA) to DTO [ Menu ]
		
		
		return dto;
	}

	// endregion
}

	