
package TPVNUBEGenEmpleadoRESTAzure.uiModels.DTOA;

import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenEmpleadoRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class PagoDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private float monto;
	public float getMonto () { return monto; }
	public void setMonto (float monto) { this.monto = monto; }
	
	
	/* Rol: Pago o--> Cliente */
	private ClienteDTOA cliente;
	public ClienteDTOA getCliente () { return cliente; }
	public void setCliente (ClienteDTOA cliente) { this.cliente = cliente; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public PagoDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Monto")))
			{
			 
				this.monto = (float) json.opt("Monto");
			 
			}
			

			JSONObject jsonCliente = json.optJSONObject("Cliente");
			if (jsonCliente != null)
			{
				ClienteDTOA tmp = new ClienteDTOA();
				tmp.setFromJSON(jsonCliente);
				this.cliente = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.monto != null)
			json.put("Monto", this.monto);
		
			

			if (this.cliente != null)
			{
				json.put("Cliente", this.cliente.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		CobroDTO dto = new CobroDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setMonto (this.getMonto());

		
		
		// Roles
					// TODO: from DTOA [ Cliente ] (dataType : ClienteDTOA) to DTO [ Cliente ]
		
		
		return dto;
	}

	// endregion
}

	