//
// CajaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CajaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var fondo: Double?;
	
	/* Rol: Caja o--> Pago */
	var cobros: [PagoDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.fondo = json["Fondo"].object as? Double;
		
		if (json["Cobros"] != JSON.null)
		{
			self.cobros = PagoDTOA(fromJSONObject: json["Cobros"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Fondo"] = self.fondo;
	
	
		
		dictionary["Cobros"] = self.cobros?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	