//
// CajeroDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CajeroDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	
	/* Rol: Cajero o--> Caja */
	var cajas: [CajaDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		
		if (json["Cajas"] != JSON.null)
		{
			self.cajas = [];
			for subJson in json["Cajas"].arrayValue
			{
				self.cajas!.append(CajaDTOA(fromJSONObject: subJson));
			}
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	
		
		dictionary["Cajas"] = NSNull();
		if (self.cajas != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.cajas!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["Cajas"] = arrayOfDictionary;
		}

		
		
		return dictionary;
	}
}

	