//
// CobroDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class CobroDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var monto: Float?;
	var fecha: NSDate?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.monto = json["Monto"].object as? Float;
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Monto"] = self.monto;
	
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	
		
		
		
		return dictionary;
	}
}

	