//
// ComandaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class ComandaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var fecha: NSDate?;
	var total: Double?;
	var estadoComanda: EstadoComanda?;
	var pdf: String?;
	
	/* Rol: Comanda o--> Factura */
	var factura: FacturaDTOA?;

	/* Rol: Comanda o--> Mesa */
	var mesaOfComanda: MesaDTOA?;

	/* Rol: Comanda o--> LineaComanda */
	var allLineaComandaOfComanda: [LineaComandaDTOA]?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		self.total = json["Total"].object as? Double;
		if let enumValue = json["EstadoComanda"].object as? Int
		{
			self.estadoComanda = EstadoComanda(rawValue: enumValue);
		}
		self.pdf = json["Pdf"].object as? String;
		
		if (json["Factura"] != JSON.null)
		{
			self.factura = FacturaDTOA(fromJSONObject: json["Factura"]);
		}

		if (json["MesaOfComanda"] != JSON.null)
		{
			self.mesaOfComanda = MesaDTOA(fromJSONObject: json["MesaOfComanda"]);
		}

		if (json["AllLineaComandaOfComanda"] != JSON.null)
		{
			self.allLineaComandaOfComanda = LineaComandaDTOA(fromJSONObject: json["AllLineaComandaOfComanda"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["Total"] = self.total;
	
	

	
		dictionary["EstadoComanda"] = self.estadoComanda?.rawValue;
	
	

	
		dictionary["Pdf"] = self.pdf;
	
	
		
		dictionary["Factura"] = self.factura?.toDictionary() ?? NSNull();

		dictionary["MesaOfComanda"] = self.mesaOfComanda?.toDictionary() ?? NSNull();

		dictionary["AllLineaComandaOfComanda"] = self.allLineaComandaOfComanda?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	