//
// EmpleadoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class EmpleadoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var apellidos: String?;
	var nombre: String?;
	var foto: String?;
	var pass: String?;
	var dni: String?;
	var email: String?;
	var telefono: String?;
	
	/* Rol: Empleado o--> Negocio */
	var negocio: NegocioDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.apellidos = json["Apellidos"].object as? String;
		self.nombre = json["Nombre"].object as? String;
		self.foto = json["Foto"].object as? String;
		self.pass = json["Pass"].object as? String;
		self.dni = json["Dni"].object as? String;
		self.email = json["Email"].object as? String;
		self.telefono = json["Telefono"].object as? String;
		
		if (json["Negocio"] != JSON.null)
		{
			self.negocio = NegocioDTOA(fromJSONObject: json["Negocio"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Apellidos"] = self.apellidos;
	
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Foto"] = self.foto;
	
	

	
		dictionary["Pass"] = self.pass;
	
	

	
		dictionary["Dni"] = self.dni;
	
	

	
		dictionary["Email"] = self.email;
	
	

	
		dictionary["Telefono"] = self.telefono;
	
	
		
		dictionary["Negocio"] = self.negocio?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	