//
// FacturaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class FacturaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var numero: String?;
	var fecha: NSDate?;
	var precio: Double?;
	var descripcion: String?;
	
	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.numero = json["Numero"].object as? String;
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		self.precio = json["Precio"].object as? Double;
		self.descripcion = json["Descripcion"].object as? String;
		
		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Numero"] = self.numero;
	
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["Precio"] = self.precio;
	
	

	
		dictionary["Descripcion"] = self.descripcion;
	
	
		
		
		
		return dictionary;
	}
}

	