//
// LineaPedidoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class LineaPedidoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var cantidad: Int?;
	
	/* GetAll: Plato */
	var platos: [PlatoDTOA]?;

	/* Rol: LineaPedido o--> Menu */
	var menus: MenuDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.cantidad = json["Cantidad"].object as? Int;
		
		if (json["Platos"] != JSON.null)
		{
			self.platos = [];
			for subJson in json["Platos"].arrayValue
			{
				self.platos!.append(PlatoDTOA(fromJSONObject: subJson));
			}
		}

		if (json["Menus"] != JSON.null)
		{
			self.menus = MenuDTOA(fromJSONObject: json["Menus"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Cantidad"] = self.cantidad;
	
	
		
		dictionary["Platos"] = NSNull();
		if (self.platos != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.platos!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["Platos"] = arrayOfDictionary;
		}

		dictionary["Menus"] = self.menus?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	