//
// PagoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PagoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var monto: Float?;
	
	/* Rol: Pago o--> Cliente */
	var cliente: ClienteDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.monto = json["Monto"].object as? Float;
		
		if (json["Cliente"] != JSON.null)
		{
			self.cliente = ClienteDTOA(fromJSONObject: json["Cliente"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Monto"] = self.monto;
	
	
		
		dictionary["Cliente"] = self.cliente?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	