//
// PedidoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PedidoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var fecha: NSDate?;
	var estadoPedido: EstadoComanda?;
	var total: Double?;
	
	/* Rol: Pedido o--> LineaPedido */
	var lineas: [LineaPedidoDTOA]?;

	/* Rol: Pedido o--> Factura */
	var factura: FacturaDTOA?;

	/* Rol: Pedido o--> Mesa */
	var mesaComanda: MesaDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
	
		self.fecha = NSDate.initFromString(json["Fecha"].object as? String);
		if let enumValue = json["EstadoPedido"].object as? Int
		{
			self.estadoPedido = EstadoComanda(rawValue: enumValue);
		}
		self.total = json["Total"].object as? Double;
		
		if (json["Lineas"] != JSON.null)
		{
			self.lineas = LineaPedidoDTOA(fromJSONObject: json["Lineas"]);
		}

		if (json["Factura"] != JSON.null)
		{
			self.factura = FacturaDTOA(fromJSONObject: json["Factura"]);
		}

		if (json["MesaComanda"] != JSON.null)
		{
			self.mesaComanda = MesaDTOA(fromJSONObject: json["MesaComanda"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Fecha"] = self.fecha?.toString();
	
	

	
		dictionary["EstadoPedido"] = self.estadoPedido?.rawValue;
	
	

	
		dictionary["Total"] = self.total;
	
	
		
		dictionary["Lineas"] = self.lineas?.toDictionary() ?? NSNull();

		dictionary["Factura"] = self.factura?.toDictionary() ?? NSNull();

		dictionary["MesaComanda"] = self.mesaComanda?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	