//
// PlatoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PlatoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nombre: String?;
	var stock: Double?;
	var precio: Double?;
	var foto: String?;
	
	/* Rol: Plato o--> Negocio */
	var negocioPlato: NegocioDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nombre = json["Nombre"].object as? String;
		self.stock = json["Stock"].object as? Double;
		self.precio = json["Precio"].object as? Double;
		self.foto = json["Foto"].object as? String;
		
		if (json["NegocioPlato"] != JSON.null)
		{
			self.negocioPlato = NegocioDTOA(fromJSONObject: json["NegocioPlato"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Stock"] = self.stock;
	
	

	
		dictionary["Precio"] = self.precio;
	
	

	
		dictionary["Foto"] = self.foto;
	
	
		
		dictionary["NegocioPlato"] = self.negocioPlato?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	