//
// RolCajeroDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class RolCajeroDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	
	/* Rol: RolCajero o--> Cajero */
	var cajero: CajeroDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		
		if (json["Cajero"] != JSON.null)
		{
			self.cajero = CajeroDTOA(fromJSONObject: json["Cajero"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	
		
		dictionary["Cajero"] = self.cajero?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	