//
// RolCamareroDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class RolCamareroDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	
	/* Rol: RolCamarero o--> Camarero */
	var camarero: CamareroDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		
		if (json["Camarero"] != JSON.null)
		{
			self.camarero = CamareroDTOA(fromJSONObject: json["Camarero"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	
		
		dictionary["Camarero"] = self.camarero?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	