	
		//
		// CajaFechaDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class CajaFechaDTO 	    {
		 
				var fecha: NSDate?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var idCaja: String?;
				    	 
		 
				var total: String?;
				    	 
		 
				var caja_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


				
					dictionary["fecha"] = self.fecha?.toString();
				

				
					dictionary["id"] = self.id;
				

				
					dictionary["idCaja"] = self.idCaja;
				

				
					dictionary["total"] = self.total;
				

					dictionary["caja_oid"] = self.caja_oid;
			
						
				return dictionary;
			}
		}
		
	