	
		//
		// EmpleadoDTO.swift
		// 
		// Code autogenerated. Do not modify this file.
		//
		
		import Foundation
		import SwiftyJSON
	
		 class EmpleadoDTO 	    {
		 
				var negocio_oid: Int?;
				    	 
		 
				var nombre: String?;
				    	 
		 
				var apellidos: String?;
				    	 
		 
				var pass: String?;
				    	 
		 
				var foto: String?;
				    	 
		 
				var comanda_oid: [Int]?;
				    	 
		 
				var id: Int?;
				    	 
		 
				var dni: String?;
				    	 
		 
				var email: String?;
				    	 
		 
				var telefono: String?;
				    	 
		 
				var cobro_oid: [Int]?;
				    	 
	   	   
			// MARK: - Constructor
			
			
		
			init ()
			{
				// Empty constructor
			}
			 func toDictionary() -> [String : AnyObject]
		
		   
			{
				var dictionary: [String : AnyObject] = [:];
				
			


					dictionary["negocio_oid"] = self.negocio_oid;
			

				
					dictionary["nombre"] = self.nombre;
				

				
					dictionary["apellidos"] = self.apellidos;
				

				
					dictionary["pass"] = self.pass;
				

				
					dictionary["foto"] = self.foto;
				

					dictionary["comanda_oid"] = self.comanda_oid;
			

				
					dictionary["id"] = self.id;
				

				
					dictionary["dni"] = self.dni;
				

				
					dictionary["email"] = self.email;
				

				
					dictionary["telefono"] = self.telefono;
				

					dictionary["cobro_oid"] = self.cobro_oid;
			
						
				return dictionary;
			}
		}
		
	