
package TPVNUBEGenTpvhostRESTAzure.uiModels.DTOA;

import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.*;
import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class EmpresaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private String nombre;
	public String getNombre () { return nombre; }
	public void setNombre (String nombre) { this.nombre = nombre; }
	
	private String direccion;
	public String getDireccion () { return direccion; }
	public void setDireccion (String direccion) { this.direccion = direccion; }
	
	private String cif;
	public String getCif () { return cif; }
	public void setCif (String cif) { this.cif = cif; }
	
	private String email;
	public String getEmail () { return email; }
	public void setEmail (String email) { this.email = email; }
	
	private java.util.Date fechaconstitucion;
	public java.util.Date getFechaconstitucion () { return fechaconstitucion; }
	public void setFechaconstitucion (java.util.Date fechaconstitucion) { this.fechaconstitucion = fechaconstitucion; }
	
	private String telefono;
	public String getTelefono () { return telefono; }
	public void setTelefono (String telefono) { this.telefono = telefono; }
	
	private String ciudad;
	public String getCiudad () { return ciudad; }
	public void setCiudad (String ciudad) { this.ciudad = ciudad; }
	
	private String pais;
	public String getPais () { return pais; }
	public void setPais (String pais) { this.pais = pais; }
	
	private String cp;
	public String getCp () { return cp; }
	public void setCp (String cp) { this.cp = cp; }
	
	private String provincia;
	public String getProvincia () { return provincia; }
	public void setProvincia (String provincia) { this.provincia = provincia; }
	
	
	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public EmpresaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Nombre")))
			{
			 
				this.nombre = (String) json.opt("Nombre");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Direccion")))
			{
			 
				this.direccion = (String) json.opt("Direccion");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Cif")))
			{
			 
				this.cif = (String) json.opt("Cif");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Email")))
			{
			 
				this.email = (String) json.opt("Email");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Fechaconstitucion")))
			{
			 
			 	String stringDate = (String) json.opt("Fechaconstitucion");
				this.fechaconstitucion = DateUtils.stringToDateFormat(stringDate);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Telefono")))
			{
			 
				this.telefono = (String) json.opt("Telefono");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Ciudad")))
			{
			 
				this.ciudad = (String) json.opt("Ciudad");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Pais")))
			{
			 
				this.pais = (String) json.opt("Pais");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Cp")))
			{
			 
				this.cp = (String) json.opt("Cp");
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Provincia")))
			{
			 
				this.provincia = (String) json.opt("Provincia");
			 
			}
			
			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.nombre != null)
			json.put("Nombre", this.nombre);
		
		
		  if (this.direccion != null)
			json.put("Direccion", this.direccion);
		
		
		  if (this.cif != null)
			json.put("Cif", this.cif);
		
		
		  if (this.email != null)
			json.put("Email", this.email);
		
		
		  if (this.fechaconstitucion != null)
			json.put("Fechaconstitucion", DateUtils.dateToFormatString(this.fechaconstitucion));
		
		
		  if (this.telefono != null)
			json.put("Telefono", this.telefono);
		
		
		  if (this.ciudad != null)
			json.put("Ciudad", this.ciudad);
		
		
		  if (this.pais != null)
			json.put("Pais", this.pais);
		
		
		  if (this.cp != null)
			json.put("Cp", this.cp);
		
		
		  if (this.provincia != null)
			json.put("Provincia", this.provincia);
		
			
			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		EmpresaDTO dto = new EmpresaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setNombre (this.getNombre());

	dto.setDireccion (this.getDireccion());

	dto.setCif (this.getCif());

	dto.setEmail (this.getEmail());

	dto.setFechaconstitucion (this.getFechaconstitucion());

	dto.setTelefono (this.getTelefono());

	dto.setCiudad (this.getCiudad());

	dto.setPais (this.getPais());

	dto.setCp (this.getCp());

	dto.setProvincia (this.getProvincia());

		
		
		// Roles
		
		
		return dto;
	}

	// endregion
}

	