
package TPVNUBEGenTpvhostRESTAzure.uiModels.DTOA;

import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.*;
import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.utils.*;
import TPVNUBEGenTpvhostRESTAzure.uiModels.DTO.enumerations.*;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Code autogenerated. Do not modify this file.
 */
public class MesaDTOA extends DTOA
{
	// region - Members, getters and setters

	private Integer id;
	public Integer getId () { return id; }
	public void setId (Integer id) { this.id = id; }

	
	private EstadoMesa estado;
	public EstadoMesa getEstado () { return estado; }
	public void setEstado (EstadoMesa estado) { this.estado = estado; }
	
	private Integer numero;
	public Integer getNumero () { return numero; }
	public void setNumero (Integer numero) { this.numero = numero; }
	
	
	/* Rol: Mesa o--> Negocio */
	private NegocioDTOA negocioMesa;
	public NegocioDTOA getNegocioMesa () { return negocioMesa; }
	public void setNegocioMesa (NegocioDTOA negocioMesa) { this.negocioMesa = negocioMesa; }

	
	
	// endregion
	
	
	
	// region - Constructor and JSON <-> DTOA <-> DTO
	
	public MesaDTOA ()
	{
		// Empty constructor
	}
	
	@Override
	public void setFromJSON (JSONObject json)
	{
		try
		{
			if (!JSONObject.NULL.equals(json.opt("Id")))
			{
				this.id = (Integer) json.opt("Id");
			}
			

			if (!JSONObject.NULL.equals(json.opt("Estado")))
			{
				int enumRawValue = (int) json.opt("Estado");
				this.estado = EstadoMesa.fromRawValue(enumRawValue);
			 
			}

			if (!JSONObject.NULL.equals(json.opt("Numero")))
			{
			 
				this.numero = (Integer) json.opt("Numero");
			 
			}
			

			JSONObject jsonNegocioMesa = json.optJSONObject("NegocioMesa");
			if (jsonNegocioMesa != null)
			{
				NegocioDTOA tmp = new NegocioDTOA();
				tmp.setFromJSON(jsonNegocioMesa);
				this.negocioMesa = tmp;
			}

			
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public JSONObject toJSON ()
	{
		JSONObject json = new JSONObject();
		
		try
		{
			if (this.id != null){
				json.put("Id", this.id);
			}
			
		
		  if (this.estado != null)
			json.put("Estado", this.estado.getRawValue());
		
		
		  if (this.numero != null)
			json.put("Numero", this.numero.intValue());
		
			

			if (this.negocioMesa != null)
			{
				json.put("NegocioMesa", this.negocioMesa.toJSON());
			}

			
		}
		catch (JSONException e)
		{
			e.printStackTrace();
		}
		
		return json;
	}
	
	@Override 
	public IDTO toDTO ()
	{
		MesaDTO dto = new MesaDTO ();
		
		// Attributes
		
	dto.setId (this.getId());

		
	dto.setEstado (this.getEstado());

	dto.setNumero (this.getNumero());

		
		
		// Roles
					// TODO: from DTOA [ NegocioMesa ] (dataType : NegocioDTOA) to DTO [ Negocio ]
		
		
		return dto;
	}

	// endregion
}

	