//
// Enumerations.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation


enum EstadoComanda: Int
{
	case Comanda = 1
	case Preparado = 2
	case Rechazado = 3
}

enum EstadoCompraProveedor: Int
{
	case Pendiente = 1
	case Pagado = 2
	case Anulado = 3
}

enum EstadoMesa: Int
{
	case Disponible = 1
	case Ocupado = 2
	case PendientePago = 3
}

	