//
// MesaDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class MesaDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var estado: EstadoMesa?;
	var numero: Int?;
	
	/* Rol: Mesa o--> Negocio */
	var negocioMesa: NegocioDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		if let enumValue = json["Estado"].object as? Int
		{
			self.estado = EstadoMesa(rawValue: enumValue);
		}
		self.numero = json["Numero"].object as? Int;
		
		if (json["NegocioMesa"] != JSON.null)
		{
			self.negocioMesa = NegocioDTOA(fromJSONObject: json["NegocioMesa"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Estado"] = self.estado?.rawValue;
	
	

	
		dictionary["Numero"] = self.numero;
	
	
		
		dictionary["NegocioMesa"] = self.negocioMesa?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	