//
// PlatoDTOA.swift
// 
// Code autogenerated. Do not modify this file.
//

import Foundation
import SwiftyJSON
		
class PlatoDTOA : DTOA
{
	// MARK: - Properties

	var id: Int?;
	
	var nombre: String?;
	var precio: Double?;
	var foto: String?;
	
	/* Rol: Plato o--> LineaPlato */
	var lineasPlato: [LineaPlatoDTOA]?;

	/* Rol: Plato o--> Negocio */
	var negocioPlato: NegocioDTOA?;

	
	
	
	
	// MARK: - Constructor
	
	init ()
	{
		// Empty constructor
	}
	
	
	
	// MARK: - JSON <-> DTOA
	
	required init (fromJSONObject json: JSON)
	{
		self.id = json["Id"].object as? Int
		
	
		self.nombre = json["Nombre"].object as? String;
		self.precio = json["Precio"].object as? Double;
		self.foto = json["Foto"].object as? String;
		
		if (json["LineasPlato"] != JSON.null)
		{
			self.lineasPlato = [];
			for subJson in json["LineasPlato"].arrayValue
			{
				self.lineasPlato!.append(LineaPlatoDTOA(fromJSONObject: subJson));
			}
		}

		if (json["NegocioPlato"] != JSON.null)
		{
			self.negocioPlato = NegocioDTOA(fromJSONObject: json["NegocioPlato"]);
		}

		
	}
	
	func toDictionary() -> [String : AnyObject]
	{
		var dictionary: [String : AnyObject] = [:];
		
		dictionary["Id"] = self.id;
		
	

	
		dictionary["Nombre"] = self.nombre;
	
	

	
		dictionary["Precio"] = self.precio;
	
	

	
		dictionary["Foto"] = self.foto;
	
	
		
		dictionary["LineasPlato"] = NSNull();
		if (self.lineasPlato != nil)
		{
			var arrayOfDictionary: [[String : AnyObject]] = [];
			for item in self.lineasPlato!
			{
				arrayOfDictionary.append(item.toDictionary());
			}
			
			dictionary["LineasPlato"] = arrayOfDictionary;
		}

		dictionary["NegocioPlato"] = self.negocioPlato?.toDictionary() ?? NSNull();

		
		
		return dictionary;
	}
}

	